-- MySQL Script generated by MySQL Workbench
-- 12/11/15 16:54:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library` DEFAULT CHARACTER SET utf8 ;
USE `library` ;

-- -----------------------------------------------------
-- Table `library`.`BookStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`BookStatus` (
  `IdBookStatus` TINYINT(1) NOT NULL COMMENT 'уникальный код записи',
  `BookStatusName` VARCHAR(50) NOT NULL COMMENT 'наименование статуса',
  PRIMARY KEY (`IdBookStatus`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COMMENT = 'статус книги';


-- -----------------------------------------------------
-- Table `library`.`Card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`Card` (
  `IdCard` INT NOT NULL AUTO_INCREMENT COMMENT 'уникальный код книги',
  `Author` VARCHAR(100) NOT NULL COMMENT 'автор(ы)',
  `Title` VARCHAR(100) NOT NULL COMMENT 'название',
  `Isbn` VARCHAR(25) NULL COMMENT 'международный стандартный книжный номер',
  `YearPublication` INT(4) NULL COMMENT 'дата публикации',
  PRIMARY KEY (`IdCard`),
  INDEX `TitleIdx` (`Title` ASC),
  INDEX `AuthorIdx` (`Author` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8
COMMENT = 'книги';


-- -----------------------------------------------------
-- Table `library`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`Book` (
  `IdBook` INT NOT NULL AUTO_INCREMENT COMMENT 'уникальный код книги',
  `InventoryNumber` VARCHAR(25) NOT NULL COMMENT 'инвентарный номер',
  `IdBookStatus` TINYINT(1) NOT NULL COMMENT 'код статуса книги (выдана на абонемент, в читальном зале, в библиотеке)',
  `IdCard` INT NULL,
  PRIMARY KEY (`IdBook`),
  INDEX `FkIdBookStatusIdx` (`IdBookStatus` ASC),
  INDEX `FkIdCardIdx` (`IdCard` ASC),
  CONSTRAINT `FkIdBookStatus`
    FOREIGN KEY (`IdBookStatus`)
    REFERENCES `library`.`BookStatus` (`IdBookStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FkIdCard`
    FOREIGN KEY (`IdCard`)
    REFERENCES `library`.`Card` (`IdCard`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8
COMMENT = 'книги';


-- -----------------------------------------------------
-- Table `library`.`UserRole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`UserRole` (
  `IdUserRole` TINYINT(1) NOT NULL COMMENT 'уникальный код',
  `RoleName` VARCHAR(50) NOT NULL COMMENT 'роль пользователя',
  PRIMARY KEY (`IdUserRole`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COMMENT = 'статус пользователя';


-- -----------------------------------------------------
-- Table `library`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`User` (
  `IdUser` INT NOT NULL AUTO_INCREMENT COMMENT 'код читателя',
  `Surname` VARCHAR(30) NOT NULL COMMENT 'фамилия',
  `Name` VARCHAR(30) NOT NULL COMMENT 'имя',
  `Patronymic` VARCHAR(30) NOT NULL COMMENT 'отчество',
  `Subscription` VARCHAR(20) NULL COMMENT 'номер абонемента',
  `Address` VARCHAR(100) NULL COMMENT 'адрес',
  `PhoneHome` VARCHAR(20) NULL DEFAULT NULL COMMENT 'телефон домашний',
  `PhoneMobile` VARCHAR(20) NULL DEFAULT NULL COMMENT 'телефон мобильный',
  `Email` VARCHAR(50) NULL COMMENT 'e-mail',
  `IdUserRole` TINYINT(1) NOT NULL COMMENT 'статус пользователя',
  `Login` VARCHAR(50) NOT NULL COMMENT 'Логин',
  `Password` CHAR(32) NOT NULL COMMENT 'MD5 хэш пароля',
  PRIMARY KEY (`IdUser`),
  INDEX `FkIdUserRoleIdx` (`IdUserRole` ASC),
  CONSTRAINT `FkIdUserRole`
    FOREIGN KEY (`IdUserRole`)
    REFERENCES `library`.`UserRole` (`IdUserRole`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COMMENT = 'пользователи';


-- -----------------------------------------------------
-- Table `library`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`Order` (
  `IdOrder` INT NOT NULL AUTO_INCREMENT COMMENT 'уникальный код',
  `IdRequest` INT NULL COMMENT 'код заявки',
  `IdBook` INT NULL COMMENT 'код книги',
  `IdUser` INT NULL COMMENT 'код читателя',
  `IdLibrarian` INT NULL COMMENT 'код библиотекаря',
  `DatePlannedReturn` DATE NULL COMMENT 'планируемая дата возврата книги',
  `DateActualReturn` DATETIME NULL COMMENT 'реальная дата возврата книги',
  `DateIssue` DATETIME NULL COMMENT 'дата выдачи книги',
  `IsReadingRoom` TINYINT(1) NULL COMMENT 'признак заказа книги в читальный зал',
  PRIMARY KEY (`IdOrder`),
  INDEX `FkIdBookIdx` (`IdBook` ASC),
  INDEX `FkIdUserIdx` (`IdUser` ASC),
  INDEX `FkIdLibrarianIdx` (`IdLibrarian` ASC),
  CONSTRAINT `FkIdBook`
    FOREIGN KEY (`IdBook`)
    REFERENCES `library`.`Book` (`IdBook`),
  CONSTRAINT `FkIdUser`
    FOREIGN KEY (`IdUser`)
    REFERENCES `library`.`User` (`IdUser`),
  CONSTRAINT `FkIdLibrarian`
    FOREIGN KEY (`IdLibrarian`)
    REFERENCES `library`.`User` (`IdUser`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COMMENT = 'заказы';


-- -----------------------------------------------------
-- Table `library`.`Request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`Request` (
  `IdRequest` INT NOT NULL AUTO_INCREMENT COMMENT 'уникальный код',
  `IdCard` INT NULL COMMENT 'код книги',
  `IdUser` INT NOT NULL COMMENT 'код читателя',
  `DateRequest` DATETIME NOT NULL COMMENT 'дата оформления заказа',
  `IsReadingRoom` TINYINT(1) NULL COMMENT 'признак заказа книги в читальный зал',
  PRIMARY KEY (`IdRequest`),
  INDEX `FkIdUserRIdx` (`IdUser` ASC),
  INDEX `FkIdCardIdx` (`IdCard` ASC),
  CONSTRAINT `FkIdCardR`
    FOREIGN KEY (`IdCard`)
    REFERENCES `library`.`Card` (`IdCard`),
  CONSTRAINT `FkIdUserR`
    FOREIGN KEY (`IdUser`)
    REFERENCES `library`.`User` (`IdUser`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8
COMMENT = 'заявки';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
